[package]
name = "kwc-engine"
edition.workspace = true
version.workspace = true

[dependencies]
wgpu = "30"
winit = "0.30.13"
glam = { version = "0.30", features = ["bytemuck"] }
bytemuck = { version = "1", features = ["derive"] }
egui = "0.36.2"
egui-wgpu = "0.36.2"
egui-winit = "0.36.2"
pollster = "0.4"
log = "0.4"
